### ISSUE TITLE
MKL isn't available on M1 macs

### ISSUE THREAD

**Issue by clark2668** [icecube/ic3-labels#10]
It seems like MKL is basically only available for Intel x86_64 processors. This means M1 Mac users can't install all the dependencies for ic3-labels. I'm not sure how necessary MKL is, or if it could be made an optional dependency?

**Comment by mhuen** [comment]
It's an optional dependency for MCEq. I guess the requirement used to be MCEq[mkl] and then it got seperated out into a full requirement at some point. I removed it as a dependency. Users who want to use MCEq with mkl support will have to install it themselves. This should fix this issue.

**Comment by mhuen** [comment]
Closing as this should be fixed now

**Comment by mhuen** [comment]
Closing as it should be fixed
